basePath: /api/v1
host: 192.168.0.123:5001
info:
  contact: {}
  description: This is helper API for IoT and other things.
  title: Homestack API
  version: "1.0"
paths:
  /docker-info:
    get:
      consumes:
      - '*/*'
      description: shows docker containers/images basic information.
      parameters:
      - description: 'item type: containers or images'
        in: query
        name: items
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show docker images or containers.
      tags:
      - docker
  /docker-logs:
    get:
      consumes:
      - '*/*'
      description: shows docker logs of running container.
      parameters:
      - description: container name
        in: query
        name: container
        type: string
      - description: since when in minutes
        in: query
        name: since
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Show docker container logs.
      tags:
      - docker
  /redis-info:
    get:
      consumes:
      - '*/*'
      description: shows vibration-sensor, door-state. humiditym and washing-state.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show most used keys from Redis.
      tags:
      - redis
schemes:
- http
swagger: "2.0"
